# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package.json tsconfig.json ./
RUN npm install --omit=dev --ignore-scripts

# Copy source code
COPY src/ ./src/

# Install dev dependencies for build and build the project
RUN npm install --include=dev --ignore-scripts && \
    npm run build && \
    npm prune --omit=dev

# Ensure the built file is executable
RUN chmod +x build/index.js

# Default command: Expecting user to provide Mixpanel credentials
CMD ["node", "build/index.js"]
